### ISSUE TITLE
media screen is changed to mediascreen

### ISSUE THREAD

**Issue by karlcow** [hallvors/css-fixme#1]
When trying to fix mixi CSS.
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1057221

Reproducing on an excerpt with media only.

Original code

``` css
/*---- width over 480px ----*/
@media screen and (min-width: 482px){
body{
background-color:#ccc;
}

#page{
width:480px;
margin:0 auto;
border-right:1px solid #ccc;
border-left:1px solid #ccc;
}
}
```

Fixed code

``` css
/*---- width over 480px ----*/
@mediascreen and (min-width: 482px){
    body{
        background-color: #ccc;
    }
    #page{
        width: 480px;
        margin: 0 auto;
        border-right: 1px solid #ccc;
        border-left: 1px solid #ccc;
    }
}
```
