### ISSUE TITLE
wrong gradient not getting fixed by the current parser

### ISSUE THREAD

**Issue by karlcow** [hallvors/css-fixme#10]
See https://webcompat.com/issues/1146 for more details.

``` css
ul.top_tub li.shop_off{
    margin: 5px 0 0 5px;
    height: 30px;
    background: url(../../images/sp/icon_bear_02.png) no-repeat 5px bottom, gradient(linear, left top, left bottom, color-stop(0%,rgb(134,170,67)), color-stop(100%,rgb(90,129,31)));
    background: url(../../images/sp/icon_bear_02.png) no-repeat 5px bottom, -webkit-gradient(linear, left top, left bottom, color-stop(0%,#87AB43), color-stop(100%,#59801F));
    font-weight: bold;
}
```
