### ISSUE TITLE
Adding a rule to fix border-image

### ISSUE THREAD

**Issue by karlcow** [hallvors/css-fixme#13]
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=995140 for context. 

``` css
.foo {
    -webkit-border-image: url() 4 2 5 4;
}
```

convert to 

``` css
.foo {
    -webkit-border-image: url() 4 2 5 4;
        border-image: url() fill 4 2 5 4;
        border-style: solid;
}
```

**Comment by karlcow** [comment]
Currently the service css fix me does:

``` css
.foo{
    -webkit-border-image: url() 4 2 5 4;
    border-image: url() 4 2 5 4;
    border-style: solid;
}
```
