### ISSUE TITLE
gradients old syntax to new syntax

### ISSUE THREAD

**Issue by karlcow** [hallvors/css-fixme#18]
when there is a linear-gradient like this

``` css
.maia-button {
    background: -webkit-linear-gradient(top, #7ddc1f 0, #64c306 100%);
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0, #7ddc1f 0), color-stop(1, #64c306 100%));
    background: -moz-linear-gradient(top, #7ddc1f 0, #64c306 100%);
    background: -moz-gradient(linear, left top, left bottom, color-stop(0, #7ddc1f 0), color-stop(1, #64c306 100%));
    background: linear-gradient(top, #7ddc1f 0, #64c306 100%);
    background-color: #7ddc1f;
    border-color: #5dba00;
    font: 15px/22px 'Open sans', Arial, sans-serif;
    font-weight: 400;
    letter-spacing: .5px;
    padding: 9px 33px
}
```

it should be fixed as:

```
  background: linear-gradient(to bottom, #7ddc1f 0, #64c306 100%);
```
