### ISSUE TITLE
-webkit-keyframes is being removed and not fixed

### ISSUE THREAD

**Issue by karlcow** [hallvors/css-fixme#19]
Using https://webcompat.com/tools/cssfixme

with 

``` css
@-webkit-keyframes qli-right-spin {
    0% {
        -webkit-transform:rotate(-130deg)
    }
    50% {
        -webkit-transform:rotate(5deg)
    }
    100% {
        -webkit-transform:rotate(-130deg)
    }
}
```

we get **nothing**
