### ISSUE TITLE
Reordering the rules when the -prefixed- properties is after the standard one.

### ISSUE THREAD

**Issue by karlcow** [hallvors/css-fixme#20]
Basically some CSS are like:

``` css
.foo {
   border-radius: …
   -webkit-border-radius:…
}
```

it would be good to rewrite to: 

``` css
.foo {
   -webkit-border-radius:…
   border-radius: …
}
```
